### ISSUE TITLE
Loading Icon

### ISSUE THREAD

**Issue by OpenDEM** [Digital-Heritage-Lab/Cesium3DHeritageMap#3]
Add a loading Icon to show the state of rendering

**Comment by gorkemkurban** [comment]
Thank you for your kind suggestion @OpenDEM, we have added a loading screen.

**Comment by gorkemkurban** [comment]
Thank you for your kind suggestion @OpenDEM , we have added a loading screen.

**Comment by OpenDEM** [comment]
Thanks a lot Görkem!
